before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - "6"
      - "7"
    ignore:
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
    main: ./cmd/bazaar
    ldflags:
      - -s -w
archives:
  - rlcp: true
    name_template: >-
      {{ .ProjectName }}_
      {{- if eq .Os "darwin" }}macos{{- else if eq .Os "linux" }}linux{{- else if eq .Os "windows" }}windows{{- else }}{{ .Os }}{{ end }}_
      {{- if eq .Arch "amd64" }}x86_64{{- else if eq .Arch "arm64" }}aarch64{{- else }}{{ .Arch }}{{ end }}
source:
  enabled: true
  name_template: "{{ .ProjectName }}-{{ .Version }}-sources"
  format: "tar.gz"
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-dev"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
