name: Go

on: workflow_call

jobs:
  build:
    runs-on: ubuntu-latest
    needs: go-versions
    strategy:
      matrix:
        go_version: ${{ fromJSON(needs.go-versions.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go_version }}

      - name: Build
        run: make build
