name: "Unit Tests"

on: workflow_call

jobs:
  test:
    runs-on: ubuntu-latest
    needs: go-versions
    strategy:
      matrix:
        go_version: ${{ fromJSON(needs.go-versions.outputs.matrix) }}
    name: Go ${{ matrix.go_version }} unit tests
    steps:
      - uses: actions/checkout@v2

      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go_version }}

      - run: make test
