name: "Test workflow"

on:
  pull_request:
    branches:
      - latest

permissions:
  contents: write # Required to upload dist files

concurrency:
  group: ci-tests-${{ github.ref }}-1
  cancel-in-progress: true

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: build --rm-dist --snapshot

      - uses: actions/upload-artifact@v3
        with:
          name: dist
          path: ./dist/

  docker-buildx:
    needs: goreleaser
    uses: ./.github/workflows/_docker-buildx.yml
